service: aws-ofs-cognito-setup
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1
  httpApi:
    cors: true
  iamRoleStatements:
    - ${file(IAM/signupAuthorizerIAM.yaml):signupAuthorizerIAM}

functions:
  signupAuthorizerSS:
    handler: src/handlers/signupAuthorizerSS.handler
    events:
      - eventBridge:
          eventBus: 'aws-ofs-eventBus-Registeration'
          pattern:
            source:
              - user.registerSS

  signupAuthorizerFS:
    handler: src/handlers/signupAuthorizerFS.handler
    events:
      - eventBridge:
          eventBus: 'aws-ofs-eventBus-Registeration'
          pattern:
            source:
              - user.registerFS
  
  signupSSpublisher:
    handler: src/handlers/signupSSpublisher.handler
    events:
     - httpApi:
         path: /register/ss
         method: post

  signupFSpublisher:
    handler: src/handlers/signupFSpublisher.handler
    events:
     - httpApi:
         path: /register/fs
         method: post
