version: "3"
services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
  nginx:
    image: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/app
    depends_on:
      - app