service: aws-ofs-proxy
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1
  httpApi:
    cors: true
  iamRoleStatements:
    - ${file(IAM/SecretsManagerIAM.yaml):SecretsManagerIAM}
functions:
  predictor:
    handler: src/handlers/predictor.handler
    events: 
     - httpApi:
         path: /predictor
         method: post

  predictableFreelancingServices:
    handler: src/handlers/predictableFreelancingServices.handler
    events: 
     - httpApi:
         path: /predictableFreelancingServices/{threshold}
         method: get

  updateModel:
    handler: src/handlers/updateModel.handler
    events: 
     - httpApi:
         path: /updateModel/{threshold}
         method: get