VerticalsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: VerticalsTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
