name: Deploy master branch

on:
  push:
    branches:
      - main

jobs:
  Vunerabilities_Check:
    name: Vunerabilities Check of all microservices
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: install Snyk CLI
      run: npm install -g snyk
    - name: Verticals microservice security check
      working-directory: src/aws-ofs-verticals-microservice
      run: snyk test
    - name: Freelancing microservice security check
      working-directory: src/aws-ofs-freelancing-microservice
      run: snyk test
    - name: Status microservice security check
      working-directory: src/aws-ofs-status-microservice
      run: snyk test


    



  # Build_Verticals_Microservice:
  #   name: Verticals microservice deployment
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: src/aws-ofs-verticals-microservice
  #   strategy:
  #     matrix:
  #       node-version: [16.x]
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: using NodeJS
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #   - run: npm ci
  #   - name: Run unit tests
  #     run: npm test
  #   - name: Install Serverless Framework
  #     run: npm install -g serverless
  #   - name: Serverless AWS authentication
  #     run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #   - name: Deploy verticals microservice to AWS
  #     run: serverless deploy


  # Build_Freelancing_Microservice:
  #   # needs: Build_Verticals_Microservice
  #   name: freelancing microservice deployment
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: src/aws-ofs-freelancing-microservice
  #   strategy:
  #     matrix:
  #       node-version: [16.x]
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #   - run: npm ci
  #   - name: Run unit tests
  #     run: npm test
  #   - name: Install Serverless Framework
  #     run: npm install -g serverless
  #   - name: Serverless AWS authentication
  #     run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #   - name: Deploy verticals microservice to AWS
  #     run: serverless deploy

  # Build_Status_Microservice:
  #   # needs: [Build_Verticals_Microservice,Build_Freelancing_Microservice]
  #   name: freelancing status microservice deployment
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: src/aws-ofs-status-microservice
  #   strategy:
  #     matrix:
  #       node-version: [16.x]
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #   - run: npm ci
  #   - name: Run unit tests
  #     run: npm test
  #   - name: Install Serverless Framework
  #     run: npm install -g serverless
  #   - name: Serverless AWS authentication
  #     run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #   - name: Deploy verticals microservice to AWS
  #     run: serverless deploy
