name: Deploy master branch

on:
  push:
    branches:
      - main

jobs:
  Build_Verticals_Microservice:
    name: verticals microservice deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/aws-ofs-verticals-microservice
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: serverless.yml
    - uses: serverless/github-action@v3.1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SLS_INTERACTIVE_SETUP_ENABLE: 1
    - run: serverless deploy

  # Build_Freelancing_Microservice:
  #   needs: Build_Verticals_Microservice
  #   name: freelancing microservice deployment
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: src/aws-ofs-freelancing-microservice
  #   strategy:
  #     matrix:
  #       node-version: [16.x]
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #   - run: npm ci
  #   - uses: serverless/github-action@v3.1
  #     with:
  #       args: deploy --package src/aws-ofs-freelancing-microservice
  #     env:
  #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
